#!/usr/bin/env python3

"""a simple script to generate an Gaussian Process model based on the data in a CSV
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

import numpy as np

import h5py

from argparse import ArgumentParser

#-------------------------------------------------

parser = ArgumentParser()

parser.add_argument('csv', nargs='+', type=str)

parser.add_argument('-v', '--verbose', default=False)

args = parser.parse_args()

#-------------------------------------------------

raise NotImplementedError('''\
load data
construct GP model that follows uncertainty estimates (how should I do this...)
expose control over correlation length scale through a command-line argument?

write the resulting GP into an HDF file compatible with universality
then I can draw from it and plot the resulting draws...
''')
