#!/usr/bin/env python3

"""extend an existing GP model to higher densities and pressures
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

import os

import h5py
import numpy as np

import matplotlib
matplotlib.use("Agg")
from matplotlib import pyplot as plt

from argparse import ArgumentParser

### non-standard library

import kernels

#-------------------------------------------------

parser = ArgumentParser()

#---

cgroup = parser.add_argument_group('arguments for process that we wish to extend')

cgroup.add_argument('input_hdf', type=str)
cgroup.add_argument('--max-input-pressurec2', default=None, type=float,
    help='truncate the input process to be below this pressure. Should be supplied in CGS units (g/cm^3)')

#---

egroup = parser.add_argument_group('arguments for extension to higher density')

egroup.add_argument('--pressurec2-scale', default='log', type=str,
    help='either "linear" or "log"; defines how we compute covariance kernel for extension to higher pressures')

egroup.add_argument('--max-output-pressurec2', default=1e17, type=float)
egroup.add_argument('--num-pressurec2-points', default=500, type=int,
    help='the number of grid points to be placed in the extension to higher pressures')

egroup.add_argument('config', type=str,
    help='config for the properties of the GP extension')

#---

vgroup = parser.add_argument_group('output arguments')

vgroup.add_argument('--plot', default=False, action='store_true')
vgroup.add_argument('--output-hdf', type=str, default=None)
vgroup.add_argument('-v', '--verbose', default=False, action='store_true')

#---

args = parser.parse_args()

if args.output_hdf is None:
    args.output_hdf = 'extended_'+os.path.basename(args.input_hdf)

#-------------------------------------------------

if args.verbose:
    print('loading : '+args.input_hdf)

with h5py.File(args.input_hdf, 'r') as obj:
    group = obj[list(obj.keys())[0]]

    attrs = dict(group.attrs.items())

    input_pc2 = np.exp(group['mean']['log(pressurec2)'][:])
    input_phi = group['mean']['phi'][:] # for the moment, stick with the assumption that the maximum sound speed is 1

    input_cov = group['cov'][...]

#------------------------

# truncated initial process at user-defined maximum pressure
if args.max_input_pressurec2 is not None:
    max_input_pc2 = np.max(input_pc2)

    if max_input_pc2 > args.max_input_pressurec2:
        if args.verbose:
            print('truncating input pressurec2 to be <= %.6e g/cm^3'%args.max_input_pressurec2)
        keep = np.arange(len(input_pc2))[input_pc2 <= args.max_input_pressurec2]
        if not len(keep):
            raise RuntimeError('cannot discard all input samples!')
        keep = keep[-1]

        input_pc2 = input_pc2[:keep]
        input_phi = input_phi[:keep]

        input_cov = input_cov[:keep,:keep]

    elif args.verbose:
        print('maximum input pressurece (%.6e g/cm^3) already less than requested maximum (%.6e g/cm^3)' % \
            (max_input_pc2, args.max_input_pressurec2))

#-------------------------------------------------

# now set up additional pressure grid
low_pressurec2 = np.max(input_pc2)

if args.pressurec2_scale == 'linear':
    if args.verbose:
        print('placing extension to higher pressures linearly with %d points between (%.6e, %.6e) g/cm^3' % \
            (args.num_pressurec2_points, low_pressurec2, args.max_output_pressurec2))

    ### do not repeat first point, so only grab the results starting at the 2nd point
    extra_pc2 = np.linspace(low_pressurec2, args.max_output_pressurec2, args.num_pressurec2_points+1)[1:]

elif args.pressurec2_scale == 'log':
    if args.verbose:
        print('placing extension to higher pressures logarithmically with %d points between (%.6e, %.6e) g/cm^3' % \
            (args.num_pressurec2_points, low_pressurec2, args.max_output_pressurec2))

    ### do not repeat first point, so only grab the results starting at the 2nd point
    extra_pc2 = np.logspace(
        np.log10(low_pressurec2),
        np.log10(args.max_output_pressurec2),
        args.num_pressurec2_points+1,
    )[1:]

else:
    raise ValueError('could not understand --pressurec2-scale=%s'%args.pc2_scale)

#------------------------

# set up covariance matrix
# note that we use the exact pressures from the input process

if args.verbose:
    print('computing prior covariance matrix')

kernel = kernels.parse(args.config, verbose=args.verbose)

if args.pressurec2_scale == 'linear':
    input_x = input_pc2
    extra_x = extra_pc2

elif args.pressurec2_scale == 'log':
    input_x = np.log(input_pc2)
    extra_x = np.log(extra_pc2)

else:
    raise ValueError('--pressurec2-scale=%s not understood!' % args.pressurec2_scale)

total_x = np.concatenate((input_x, extra_x))

### input - input
prior_cov_input_input = kernel.cov(input_x, input_x)

### input - total and total - input
prior_cov_input_total = kernel.cov(input_x, total_x)
prior_cov_total_input = np.transpose(prior_cov_input_total)

### extension - extension
prior_cov_total_total = kernel.cov(total_x, total_x)

#-------------------------------------------------

# figure out prior mean function
# take this to be an extrapolation of the input process's behavior

if args.verbose:
    print('computing prior mean as a cubic fit to input process')

p3, p2, p1, p0 = np.polyfit(input_x, input_phi, 3) # use a 3rd order polynomial
                                                   # will force phi to decrease as part of the extrapolation

input_mean = p3*input_x**3 + p2*input_x**2 + p1*input_x + p0
total_mean = p3*total_x**3 + p2*total_x**2 + p1*total_x + p0

#-------------------------------------------------

# condition total GP on the input GP

if args.verbose:
    print('conditioning prior process on input process')

# this treats the input process as a noisey observation
# it should work if we do not infer the function exactly at the input points
# BUT I want to infer the function exactly at the input points to make sure I follow the input process closely...
invcov_input_input = np.linalg.inv(input_cov + prior_cov_input_input)

### FIXME:
# make sure the expression above works when I infer the function at the input points
# or derive a new expression that does
# perhaps we can "jitter" the evaluation points to be slightly away from the input points, but very close (small compared to correlation lengths)
# maybe that will tie the function at the test points tightly-enough to the input points?

conditioned_mean = total_mean + prior_cov_total_input @ invcov_input_input @ (input_phi - input_mean)
conditioned_cov = prior_cov_total_total - prior_cov_total_input @ invcov_input_input @ prior_cov_input_total

#------------------------

# plot the conditioned process

if args.plot:
    if args.verbose:
        print('plotting conditioned process')

    fig = plt.figure()
    ax = fig.gca()

    # now actually plot
    raise NotImplementedError('''
make a plot of the conditioned process
    mean and 1D stdv (envelop plot)
    overlay with a few realizations?
    also plot a heat-map of correlation matrix
''')

    # save
    figname = args.output_hdf[:-3] + 'png'
    if args.verbose:
        print('    saving : '+figname)
    fig.savefig(figname)
    plt.close(fig)

#------------------------

# save
if args.verbose:
    print('writing : '+args.output_hdf)

with h5py.File(args.output_hdf, 'w') as obj:
    group = obj.create_group(os.path.basename(args.input_hdf)[:-4])

    # store command-line arguments
    group.attrs.create('input_hdf', args.input_hdf)
    group.attrs.create('max_input_pressurec2', args.max_input_pressurec2)

    group.attrs.create('pressurec2_scale', args.pressurec2_scale)
    group.attrs.create('max_output_pressurec2', args.max_output_pressurec2)
    group.attrs.create('num_pressurec2_points', args.num_pressurec2_points)

    group.attrs.create('config', args.config)

    # store process
    if args.pressurec2_scale == 'linear':
        mean = np.empty(len(total_x), dtype=[('pressurec2', float), ('phi', float)])
        mean['pressurec2'] = total_mean

    elif args.pressurec2_scale == 'log':
        mean = np.empty(len(total_x), dtype=[('log(pressurec2)', float), ('phi', float)])
        mean['log(pressurec2)'] = total_mean

    else:
        raise ValueError('could not understand --pressurec2-scale=%s'%args.pressurec2_scale)

    mean['phi'] = conditioned_mean

    group.create_dataset('mean', data=mean)
    group.create_dataset('cov', data=conditioned_cov)
