#!/bin/bash

### a quick script to record workflow
### Reed Essick (reed.essick@gmail.com)

# convert to csv and CGS units

echo \
./dat2csv \
    *.dat \
    --plot \
    --verbose

# build simple GP models based on the uncertainty envelopes

#SCALE=0.75
#SCALE_NAME="00d75"

SCALE=0.50
SCALE_NAME="00d50"

LENGTH=4.0
LENGTH_NAME="004d000"

echo \
./csv2gp \
    *.csv \
    --pressurec2-range "1e9" "3e13" \
    --num-pressure-points "501" \
    --scale $SCALE \
    --correlation-length $LENGTH \
    --plot \
    --num-draws 5 \
    --verbose

# draw from GP model and integrate to get pressure - energy_density - baryon_density curves

for ORDER in "N2LO" "N3LO"
do

    echo \
    ./gp2eos \
        "EMN450_${ORDER}_MBPT3_beta_equilibrium_eft_bands_${SCALE_NAME}_${LENGTH_NAME}.hdf" \
        "EMN450_${ORDER}_MBPT3_beta_equilibrium_eft_bands.csv" \
        --reference-pressurec2 "1.0e9" \
        --reference-pressurec2 "3.0e9" \
        --reference-pressurec2 "6.0e9" \
        --reference-pressurec2 "1.0e10" \
        --reference-pressurec2 "3.0e10" \
        --reference-pressurec2 "6.0e10" \
        --reference-pressurec2 "1.0e11" \
        --reference-pressurec2 "2.0e11" \
        --reference-pressurec2 "3.0e11" \
        --reference-pressurec2 "4.0e11" \
        --reference-pressurec2 "5.0e11" \
        --reference-pressurec2 "6.0e11" \
        --reference-pressurec2 "7.0e11" \
        --reference-pressurec2 "8.0e11" \
        --reference-pressurec2 "9.0e11" \
        --reference-pressurec2 "1.0e12" \
        --reference-pressurec2 "2.0e12" \
        --reference-pressurec2 "3.0e12" \
        --reference-pressurec2 "4.0e12" \
        --reference-pressurec2 "5.0e12" \
        --reference-pressurec2 "6.0e12" \
        --reference-pressurec2 "7.0e12" \
        --reference-pressurec2 "8.0e12" \
        --reference-pressurec2 "9.0e12" \
        --reference-pressurec2 "1.0e13" \
        --reference-pressurec2 "1.5e13" \
        --reference-pressurec2 "2.0e13" \
        --reference-pressurec2 "2.5e13" \
        --reference-pressurec2 "3.0e13" \
        --num-draws 1000 \
        --plot \
        --verbose

done

# extend GP models to higher pressures

for ORDER in "N2LO" "N3LO"
do

#    echo \
    ./extend-gp \
        "EMN450_${ORDER}_MBPT3_beta_equilibrium_eft_bands_${SCALE_NAME}_${LENGTH_NAME}.hdf" \
        prior_kernel.ini \
        --output-hdf "extended-EMN450_${ORDER}_MBPT3_beta_equilibrium_eft_bands_${SCALE_NAME}_${LENGTH_NAME}.hdf" \
        --max-input-pressurec2 1e13 \
        --pressurec2-scale 'log' \
        --max-output-pressurec2 1e17 \
        --num-pressurec2-points 500 \
        --verbose \
#        --plot \

done
