#!/bin/bash

### a quick script to make envelope plots
### Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

declare -A YMIN
declare -A YMAX
declare -A YLABEL
declare -A EXTRA

YMIN["R"]=" 5.0"
YMAX["R"]="25.0"
YLABEL["R"]="\$R\,[\\mathrm{km}]\$"

YMIN["Lambda"]="1.0e1"
YMAX["Lambda"]="3.0e7"
YLABEL["Lambda"]="\$\\Lambda\$"
EXTRA["Lambda"]="--logcolumn Lambda"

#-------------------------------------------------

STITCH_REF="00d00_001d000"

#-------------------------------------------------

for WIGGLE in "01d00_000d500" "00d75_001d000"
do

    for STITCH in "cond" "trunc+cond"
    do

        for YCOLUMN in "R" "Lambda"
        do

            NTwoLO="2023-06-09-EMN450_N2LO_MBPT3_beta_equilibrium_eft_bands/EMN450_N2LO_MBPT3_beta_equilibrium_eft_bands_${WIGGLE}_${STITCH}_maxpc2-1e13_hadagn_05d000_00d010/manifest-M-${YCOLUMN}-quantiles-EMN450_N2LO_MBPT3_beta_equilibrium_eft_bands_${WIGGLE}_${STITCH}_maxpc2-1e13_hadagn_05d000_00d010.csv"
            NThreeLO="2023-06-09-EMN450_N3LO_MBPT3_beta_equilibrium_eft_bands/EMN450_N3LO_MBPT3_beta_equilibrium_eft_bands_${WIGGLE}_${STITCH}_maxpc2-1e13_hadagn_05d000_00d010/manifest-M-${YCOLUMN}-quantiles-EMN450_N3LO_MBPT3_beta_equilibrium_eft_bands_${WIGGLE}_${STITCH}_maxpc2-1e13_hadagn_05d000_00d010.csv"

            TAG="M-${YCOLUMN}-2023-06-09-EMN450_NXLO_MBPT3_beta_equilibrium_eft_bands_${WIGGLE}_${STITCH}_maxpc2-1e13_hadagn_05d000_00d010"

            ### grab reference processes (zero width within EFT band)
            NTwoLO_ref="2023-06-09-EMN450_N2LO_MBPT3_beta_equilibrium_eft_bands/EMN450_N2LO_MBPT3_beta_equilibrium_eft_bands_${WIGGLE}_${STITCH_REF}_maxpc2-1e13_hadagn_05d000_00d010/manifest-M-${YCOLUMN}-quantiles-EMN450_N2LO_MBPT3_beta_equilibrium_eft_bands_${WIGGLE}_${STITCH_REF}_maxpc2-1e13_hadagn_05d000_00d010.csv"
            NThreeLO_ref="2023-06-09-EMN450_N3LO_MBPT3_beta_equilibrium_eft_bands/EMN450_N3LO_MBPT3_beta_equilibrium_eft_bands_${WIGGLE}_${STITCH_REF}_maxpc2-1e13_hadagn_05d000_00d010/manifest-M-${YCOLUMN}-quantiles-EMN450_N3LO_MBPT3_beta_equilibrium_eft_bands_${WIGGLE}_${STITCH_REF}_maxpc2-1e13_hadagn_05d000_00d010.csv"

            ### make the plot

#            echo \
            plot-quantiles \
                "M" $YCOLUMN 0.10 3.00 \
                --column-label "M" "\$M\,[M_\\odot]\$" \
                --column-label $YCOLUMN ${YLABEL[$YCOLUMN]} \
                --ymin ${YMIN[$YCOLUMN]} \
                --ymax ${YMAX[$YCOLUMN]} \
                ${EXTRA[$YCOLUMN]} \
                -s "N2LO" $NTwoLO \
                --color "N2LO" "blue" \
                --alpha "N2LO" 0.10 \
                --filled "N2LO" \
                -s "N2LO-fixed" $NTwoLO_ref \
                --color "N2LO-fixed" "cornflowerblue" \
                --alpha "N2LO-fixed" 0.10 \
                --filled "N2LO-fixed" \
                -s "N3LO" $NThreeLO \
                --color "N3LO" "r" \
                --alpha "N3LO" 0.10 \
                --filled "N3LO" \
                -s "N3LO-fixed" $NThreeLO_ref \
                --color "N3LO-fixed" "orange" \
                --alpha "N3LO-fixed" 0.10 \
                --filled "N3LO-fixed" \
                --num-points 501 \
                --quantile 0.05 \
                --quantile 0.25 \
                --quantile 0.50 \
                --quantile 0.75 \
                --quantile 0.95 \
                --quantile-type "sym" \
                --output-dir "." \
                --tag $TAG \
                --figtype png --figtype pdf \
                --legend \
                --Verbose \
            || exit 1

            #---

            # plot zooms

#            echo \
            plot-quantiles \
                "M" $YCOLUMN 0.10 0.55 \
                --column-label "M" "\$M\,[M_\\odot]\$" \
                --column-label $YCOLUMN ${YLABEL[$YCOLUMN]} \
                --ymin ${YMIN[$YCOLUMN]} \
                --ymax ${YMAX[$YCOLUMN]} \
                ${EXTRA[$YCOLUMN]} \
                -s "N2LO" $NTwoLO \
                --color "N2LO" "blue" \
                --alpha "N2LO" 0.10 \
                --filled "N2LO" \
                -s "N2LO-fixed" $NTwoLO_ref \ 
                --color "N2LO-fixed" "cornflowerblue" \
                --alpha "N2LO-fixed" 0.10 \
                --filled "N2LO-fixed" \
                -s "N3LO" $NThreeLO \
                --color "N3LO" "r" \
                --alpha "N3LO" 0.10 \
                --filled "N3LO" \
                -s "N3LO-fixed" $NThreeLO_ref \
                --color "N3LO-fixed" "orange" \
                --alpha "N3LO-fixed" 0.10 \
                --filled "N3LO-fixed" \
                --num-points 501 \
                --quantile 0.05 \
                --quantile 0.25 \
                --quantile 0.50 \
                --quantile 0.75 \
                --quantile 0.95 \
                --quantile-type "sym" \
                --output-dir "." \
                --tag "zoom-$TAG" \
                --figtype png --figtype pdf \
                --legend \
                --Verbose \
            || exit 1

        done
    done
done
