#!/bin/bash

### a quick script to make envelope plots
### Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

declare -A MIN
declare -A MAX
declare -A LABEL

MIN["baryon_density"]="2.8e12"
MAX["baryon_density"]="2.8e16"
LABEL["baryon_density"]="\$\\log_{10}\\rho\,[\\mathrm{g}/\\mathrm{cm}^3]\$"

MIN["energy_densityc2"]="2.8e12"
MAX["energy_densityc2"]="2.8e16"
LABEL["energy_densityc2"]="\$\\log_{10}\\varepsilon\,[\\mathrm{g}/\\mathrm{cm}^3]\$"

MIN["pressurec2"]="1.0e10"
MAX["pressurec2"]="1.0e16"
LABEL["pressurec2"]="\$\\log_{10}p/c^2\,[\\mathrm{g}/\\mathrm{cm}^3]\$"

MIN["cs2c2"]="1.0e-3"
MAX["cs2c2"]="1.0"
LABEL["cs2c2"]="\$\\log_{10}c_s^2/c^2\$"

#-------------------------------------------------

for WIGGLE in "01d00_000d500" "00d75_001d000"
do

    for STITCH in "cond" "trunc+cond"
    do

        for XCOLUMN in "baryon_density" "energy_densityc2"
        do

            for YCOLUMN in "R" "Lambda"
            do

                NTwoLO="2023-06-09-EMN450_N2LO_MBPT3_beta_equilibrium_eft_bands/EMN450_N2LO_MBPT3_beta_equilibrium_eft_bands_${WIGGLE}_${STITCH}_maxpc2-1e13_hadagn_05d000_00d010/manifest-${XCOLUMN}-${YCOLUMN}-quantiles-EMN450_N2LO_MBPT3_beta_equilibrium_eft_bands_${WIGGLE}_${STITCH}_maxpc2-1e13_hadagn_05d000_00d010.csv"
                NThreeLO="2023-06-09-EMN450_N3LO_MBPT3_beta_equilibrium_eft_bands/EMN450_N3LO_MBPT3_beta_equilibrium_eft_bands_${WIGGLE}_${STITCH}_maxpc2-1e13_hadagn_05d000_00d010/manifest-${XCOLUMN}-${YCOLUMN}-quantiles-EMN450_N3LO_MBPT3_beta_equilibrium_eft_bands_${WIGGLE}_${STITCH}_maxpc2-1e13_hadagn_05d000_00d010.csv"

                TAG="${XCOLUMN}-${YCOLUMN}-2023-06-09-EMN450_NXLO_MBPT3_beta_equilibrium_eft_bands_${WIGGLE}_${STITCH}_maxpc2-1e13_hadagn_05d000_00d010"

#                echo \
                plot-quantiles \
                    $XCOLUMN $YCOLUMN ${MIN[$XCOLUMN]} ${MAX[$XCOLUMN]} \
                    --column-label $XCOLUMN ${LABEL[$XCOLUMN]} \
                    --logcolumn $XCOLUMN \
                    --x-multiplier "0.4342944819032518" \
                    --column-label $YCOLUMN ${LABEL[$COLUMN]} \
                    --logcolumn $YCOLUMN \
                    --y-multiplier "0.4342944819032518" \
                    --ymin ${MIN[$YCOLUMN]} \
                    --ymax ${MAX[$YCOLUMN]} \
                    -s "N2LO" $NTwoLO \
                    --color "N2LO" "k" \
                    --alpha "N2LO" 0.10 \
                    --filled "N2LO" \
                    -s "N3LO" $NThreeLO \
                    --color "N3LO" "r" \
                    --alpha "N3LO" 0.10 \
                    --filled "N3LO" \
                    --num-points 501 \
                    --quantile 0.05 \
                    --quantile 0.25 \
                    --quantile 0.50 \
                    --quantile 0.75 \
                    --quantile 0.95 \
                    --quantile-type "sym" \
                    --output-dir "." \
                    --tag $TAG \
                    --figtype png --figtype pdf \
                    --legend \
                    --Verbose \
                || exit 1

            done
        done
    done
done
